export const PRODUCT_CATEGORIES = [
  'Clothing',
  'Accessories',
  'Footwear',
  'Beauty & Personal Care',
  'Electronics',
  'Mobiles & Gadgets',
  'Home & Living',
  'Kitchen & Dining',
  'Furniture',
  'Food & Beverages',
  'Grocery & Staples',
  'Health & Wellness',
  'Baby & Kids',
  'Toys & Games',
  'Books & Stationery',
  'Sports & Fitness',
  'Automotive',
  'Hardware & Tools',
  'Jewellery',
  'Bags & Luggage',
  'Pet Supplies',
  'Office Supplies',
  'Other'
] as const;
